# Generated by Django 3.0.1 on 2020-01-04 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cbjobsdata_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CbQnsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_user_id', models.CharField(max_length=60)),
                ('date_time', models.DateTimeField()),
                ('has_question', models.BooleanField(default=False)),
                ('search_question', models.CharField(max_length=100)),
                ('question_helpful', models.NullBooleanField()),
                ('wants_reply', models.NullBooleanField()),
                ('question_left', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
    ]
