# Generated by Django 3.0.1 on 2020-01-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cbqnsdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbqnsdata',
            options={'verbose_name_plural': 'Chatbot question data'},
        ),
        migrations.AlterField(
            model_name='cbqnsdata',
            name='question_left',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cbqnsdata',
            name='search_question',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CbBrowsingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_user_id', models.CharField(max_length=60)),
                ('date_time', models.DateTimeField()),
                ('is_browsing', models.NullBooleanField()),
                ('why_on_site', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'verbose_name_plural': 'Chatbot browsing data',
            },
        ),
    ]
