# Generated by Django 3.0.1 on 2020-01-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbbrowsingdata',
            name='is_browsing',
            field=models.BooleanField(default=False),
        ),
    ]
