# Generated by Django 3.0.1 on 2020-01-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='postcode',
            new_name='post_code',
        ),
    ]
