# Generated by Django 3.0.1 on 2020-01-23 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200123_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('specialism', models.CharField(max_length=100)),
                ('role_type', models.CharField(max_length=100)),
                ('description_url', models.CharField(max_length=255)),
                ('apply_url', models.CharField(max_length=255)),
                ('video_url', models.CharField(blank=True, max_length=255)),
                ('intro', models.CharField(blank=True, max_length=255)),
                ('active_job', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
        ),
    ]
