# Generated by Django 3.0.1 on 2020-01-29 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyChatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_site_url', models.CharField(max_length=255)),
                ('privacy_notice_url', models.CharField(max_length=255)),
                ('next_steps', models.CharField(max_length=255)),
                ('company_video_url', models.CharField(blank=True, max_length=255)),
                ('talent_email', models.EmailField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
