# Generated by Django 3.0.1 on 2020-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companyapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='companychatbot',
            name='benefits_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companychatbot',
            name='benefits_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
