# Generated by Django 3.0.1 on 2020-02-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_roletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RoleType'),
        ),
    ]
